---
name: "generate-exe"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-exe:
    strategy:
      matrix:
        os: [windows-latest]
    name: "Build executable"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Updating executable
        run: |
          cd app
          python main.py
          .\port_assets.bat
          mv DQXConfig.exe ../
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: DQXConfig.exe
